name: dz_delivery_restaurant
description: DZ Delivery - Application Restaurant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.0
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  fl_chart: ^0.69.2
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  vibration: ^2.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
